// Copyright 2022 wevet works All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "NativeGameplayTags.h"

// using
// *GETENUMSTRING("/Script/ProjectName.EnumName")
#define GETENUMSTRING(etype, evalue)\
	 ((FindObject<UEnum>(nullptr, TEXT(etype), true) != nullptr) ? FindObject<UEnum>(nullptr, TEXT(etype), true)->GetNameStringByIndex((int32)evalue) : FString("Invalid - UENUM() macro?"))

// Input
REDEMPTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Game_Input_Disable);

// MeleeAction
REDEMPTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_ActionMelee);
REDEMPTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_ActionMelee_ComboRequire);
REDEMPTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_ActionMelee_Combo1);
REDEMPTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_ActionMelee_Combo2);
REDEMPTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_ActionMelee_Combo3);
REDEMPTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_ActionMelee_Forbid);

// JumpAction
REDEMPTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_ActionJump);
REDEMPTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_ActionJump_Forbid);

// Dash
REDEMPTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_ActionDash);
REDEMPTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_ActionDash_Forbid);

// Crouch
REDEMPTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_ActionCrouch);
REDEMPTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_ActionCrouch_Forbid);

// TargetLockOn
REDEMPTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_TargetLock);
REDEMPTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_TargetLocking);
REDEMPTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Character_TargetLock_Forbid);

// Climbing
REDEMPTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Locomotion_ClimbingJump);
REDEMPTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Locomotion_ClimbingLedgeEnd);
REDEMPTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Locomotion_ClimbingAbort);

// Mantling
REDEMPTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Locomotion_Mantling);

// Forbid
REDEMPTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Locomotion_ForbidClimbing);
REDEMPTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Locomotion_ForbidMantling);
REDEMPTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Locomotion_ForbidMovement);
REDEMPTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Locomotion_ForbidJump);

// weapon type
REDEMPTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Weapon_Melee_Default);
REDEMPTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Weapon_Melee_Pistol);
REDEMPTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Weapon_Melee_Rifle);
REDEMPTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Weapon_Melee_Knife);

// bullet weapon state
REDEMPTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Weapon_Gun_Reload);
REDEMPTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Weapon_Gun_Fire);

// AI 
// waypoint visited
REDEMPTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_AI_Waypoint_Visited);
REDEMPTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_AI_Waypoint_UnVisited);
REDEMPTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_AI_State_Search);
REDEMPTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_AI_State_Combat);
REDEMPTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_AI_State_Patrol);

/*
* ABaseCharacter Destroy Interval
*/
#define DEFAULT_LIFESPAN 30.0f

/*
* AIPerception Sight CancelEvent Interval
*/
#define SIGHT_AGE 20.0f


#define NEARLEST_TARGET_SYNC_POINT FName(TEXT("NearlestTarget"))
#define FINISHER_TARGET_SYNC_POINT FName(TEXT("FinisherTarget"))


